// <auto-generated />
using System;
using ControlVencimientosP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlVencimientosP.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlVencimientosP.Domain.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("RutaBlob")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SubidoEn")
                        .HasColumnType("datetime2");

                    b.Property<long>("TamanioBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("VencimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VencimientoId");

                    b.ToTable("Adjuntos", (string)null);
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.AvisoEnviado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnviadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("HitoDias")
                        .HasColumnType("int");

                    b.Property<string>("ProveedorMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VencimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("VencimientoId", "HitoDias", "Canal", "DestinatarioId")
                        .IsUnique()
                        .HasDatabaseName("UX_AvisosEnviados_Idempotencia");

                    b.ToTable("AvisosEnviados", (string)null);
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("DiasAvisoDefault")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "building-2",
                            Nombre = "Habilitacion",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 60,
                            EmpresaId = 1,
                            Icono = "shield",
                            Nombre = "Seguro",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "flame-kindling",
                            Nombre = "Matafuego",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "shield-plus",
                            Nombre = "ART",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "graduation-cap",
                            Nombre = "Capacitacion",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "id-card",
                            Nombre = "Carnet",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "scroll-text",
                            Nombre = "Licencia",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 15,
                            EmpresaId = 1,
                            Icono = "wrench",
                            Nombre = "Mantenimiento",
                            Orden = 8
                        },
                        new
                        {
                            Id = 9,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "search-check",
                            Nombre = "Inspeccion",
                            Orden = 9
                        },
                        new
                        {
                            Id = 10,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 60,
                            EmpresaId = 1,
                            Icono = "file-signature",
                            Nombre = "Contrato",
                            Orden = 10
                        },
                        new
                        {
                            Id = 11,
                            Activa = true,
                            Color = "#2a78d6",
                            DiasAvisoDefault = 30,
                            EmpresaId = 1,
                            Icono = "file-text",
                            Nombre = "Otro",
                            Orden = 11
                        });
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.ConfiguracionAvisos", b =>
                {
                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("AlertaIndividualActiva")
                        .HasColumnType("bit");

                    b.Property<bool>("DigestActivo")
                        .HasColumnType("bit");

                    b.Property<string>("HitosDias")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<TimeOnly>("HoraEnvio")
                        .HasColumnType("time");

                    b.Property<int>("ReenviarVencidosCadaDias")
                        .HasColumnType("int");

                    b.Property<bool>("WhatsappActivo")
                        .HasColumnType("bit");

                    b.HasKey("EmpresaId");

                    b.ToTable("ConfiguracionesAvisos", (string)null);

                    b.HasData(
                        new
                        {
                            EmpresaId = 1,
                            AlertaIndividualActiva = true,
                            DigestActivo = true,
                            HitosDias = "60,30,15,7,1,0",
                            HoraEnvio = new TimeOnly(8, 0, 0),
                            ReenviarVencidosCadaDias = 7,
                            WhatsappActivo = false
                        });
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Destinatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CategoriasFiltro")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Activo");

                    b.ToTable("Destinatarios", (string)null);
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            CreadaEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Mi empresa",
                            ZonaHoraria = "America/Argentina/Buenos_Aires"
                        });
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ResponsableUsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ResponsableUsuarioId");

                    b.HasIndex("EmpresaId", "CategoriaId");

                    b.HasIndex("EmpresaId", "Nombre");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("RecibeAvisos")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Vencimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPorUsuarioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiasAviso")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("RenovadoPorVencimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_Vencimientos_UnoActivoPorItem")
                        .HasFilter("[Estado] = 0");

                    b.HasIndex("RenovadoPorVencimientoId");

                    b.HasIndex("EmpresaId", "Estado", "FechaVencimiento");

                    b.ToTable("Vencimientos", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Adjunto", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Vencimiento", "Vencimiento")
                        .WithMany("Adjuntos")
                        .HasForeignKey("VencimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vencimiento");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.AvisoEnviado", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Destinatario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVencimientosP.Domain.Vencimiento", "Vencimiento")
                        .WithMany()
                        .HasForeignKey("VencimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Vencimiento");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Categoria", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Empresa", "Empresa")
                        .WithMany("Categorias")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.ConfiguracionAvisos", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Empresa", "Empresa")
                        .WithOne()
                        .HasForeignKey("ControlVencimientosP.Domain.ConfiguracionAvisos", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Destinatario", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Item", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Categoria", "Categoria")
                        .WithMany("Items")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVencimientosP.Domain.Empresa", "Empresa")
                        .WithMany("Items")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVencimientosP.Domain.Usuario", "ResponsableUsuario")
                        .WithMany()
                        .HasForeignKey("ResponsableUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Empresa");

                    b.Navigation("ResponsableUsuario");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Usuario", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Vencimiento", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlVencimientosP.Domain.Item", "Item")
                        .WithMany("Vencimientos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlVencimientosP.Domain.Vencimiento", "RenovadoPor")
                        .WithMany()
                        .HasForeignKey("RenovadoPorVencimientoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Empresa");

                    b.Navigation("Item");

                    b.Navigation("RenovadoPor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlVencimientosP.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ControlVencimientosP.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Categoria", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Empresa", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Item", b =>
                {
                    b.Navigation("Vencimientos");
                });

            modelBuilder.Entity("ControlVencimientosP.Domain.Vencimiento", b =>
                {
                    b.Navigation("Adjuntos");
                });
#pragma warning restore 612, 618
        }
    }
}
